var ttr={
  "semptomlar": [
    {"id": "S001", "ad": "Ateş", "kategori": "Genel"},
    {"id": "S002", "ad": "Halsizlik", "kategori": "Genel"},
    {"id": "S003", "ad": "Kilo kaybı", "kategori": "Genel"},
    {"id": "S004", "ad": "Gece terlemesi", "kategori": "Genel"},
    {"id": "S005", "ad": "İştahsızlık", "kategori": "Genel"},
    {"id": "S006", "ad": "Yorgunluk", "kategori": "Genel"},
    {"id": "S007", "ad": "Solukluk", "kategori": "Genel"},
    {"id": "S008", "ad": "Ödem", "kategori": "Genel"},
    {"id": "S009", "ad": "Kendini hasta hissetme", "kategori": "Genel"},

    {"id": "S010", "ad": "Baş ağrısı", "kategori": "Nöro"},
    {"id": "S011", "ad": "Baş dönmesi", "kategori": "Nöro"},
    {"id": "S012", "ad": "Bilinç kaybı/baygınlık", "kategori": "Nöro"},
    {"id": "S013", "ad": "Nöbet/konvülsiyonlar", "kategori": "Nöro"},
    {"id": "S014", "ad": "Paralizi", "kategori": "Nöro"},
    {"id": "S015", "ad": "Kas güçsüzlüğü", "kategori": "Nöro"},
    {"id": "S016", "ad": "Uyuşukluk hissi", "kategori": "Nöro"},
    {"id": "S017", "ad": "Karıncalanma", "kategori": "Nöro"},
    {"id": "S018", "ad": "Hafıza kaybı", "kategori": "Nöro"},
    {"id": "S019", "ad": "Konsantrasyon güçlüğü", "kategori": "Nöro"},
    {"id": "S020", "ad": "Sersemlik hali", "kategori": "Nöro"},
    {"id": "S021", "ad": "Yürümede zorluk", "kategori": "Nöro"},
    {"id": "S022", "ad": "Tremor/titreme", "kategori": "Nöro"},
    {"id": "S023", "ad": "Kore (istemsiz hareketler)", "kategori": "Nöro"},

    {"id": "S024", "ad": "Nefes darlığı/dispne", "kategori": "Solunum"},
    {"id": "S025", "ad": "Öksürük", "kategori": "Solunum"},
    {"id": "S026", "ad": "Balgam çıkarma", "kategori": "Solunum"},
    {"id": "S027", "ad": "Hemoptizi (kanlı balgam)", "kategori": "Solunum"},
    {"id": "S028", "ad": "Hırıltılı solunum/wheezing", "kategori": "Solunum"},
    {"id": "S029", "ad": "Burun tıkanıklığı", "kategori": "Solunum"},
    {"id": "S030", "ad": "Burun akıntısı", "kategori": "Solunum"},
    {"id": "S031", "ad": "Ses kısıklığı", "kategori": "Solunum"},
    {"id": "S032", "ad": "Boğaz ağrısı", "kategori": "Solunum"},
    {"id": "S033", "ad": "Siyanoz", "kategori": "Solunum"},
    {"id": "S034", "ad": "Takipne", "kategori": "Solunum"},

    {"id": "S035", "ad": "Göğüs ağrısı", "kategori": "Kalp"},
    {"id": "S036", "ad": "Çarpıntı", "kategori": "Kalp"},
    {"id": "S037", "ad": "Taşikardi", "kategori": "Kalp"},
    {"id": "S038", "ad": "Bradikardi", "kategori": "Kalp"},
    {"id": "S039", "ad": "Ortopne", "kategori": "Kalp"},
    {"id": "S040", "ad": "Paroksismal noktürnal dispne", "kategori": "Kalp"},
    {"id": "S041", "ad": "Periferik ödem", "kategori": "Kalp"},
    {"id": "S042", "ad": "Boyunda venöz dolgunluk", "kategori": "Kalp"},
    {"id": "S043", "ad": "Senkop", "kategori": "Kalp"},
    {"id": "S044", "ad": "Soğuk terleme", "kategori": "Kalp"},

    {"id": "S045", "ad": "Karın ağrısı", "kategori": "GİS"},
    {"id": "S046", "ad": "Bulantı", "kategori": "GİS"},
    {"id": "S047", "ad": "Kusma", "kategori": "GİS"},
    {"id": "S048", "ad": "İshal", "kategori": "GİS"},
    {"id": "S049", "ad": "Kabızlık", "kategori": "GİS"},
    {"id": "S050", "ad": "Bağırsaklarda gazlanma", "kategori": "GİS"},
    {"id": "S051", "ad": "Yutkunmada güçlük", "kategori": "GİS"},
    {"id": "S052", "ad": "Sarılık", "kategori": "GİS"},
    {"id": "S053", "ad": "Hepatomegali", "kategori": "GİS"},
    {"id": "S054", "ad": "Splenomegali", "kategori": "GİS"},
    {"id": "S055", "ad": "Rektal ağrı", "kategori": "GİS"},
    {"id": "S056", "ad": "Dışkıda kan/mukus", "kategori": "GİS"},
    {"id": "S057", "ad": "Mide yanması/reflü", "kategori": "GİS"},
    {"id": "S058", "ad": "Dispepsi", "kategori": "GİS"},
    {"id": "S059", "ad": "Ağız kuruluğu", "kategori": "GİS"},
    {"id": "S060", "ad": "Ağız kokusu", "kategori": "GİS"},
    {"id": "S061", "ad": "Asit", "kategori": "GİS"},

    {"id": "S062", "ad": "Dizüri (ağrılı idrara çıkma)", "kategori": "Üriner"},
    {"id": "S063", "ad": "Poliüri", "kategori": "Üriner"},
    {"id": "S064", "ad": "Pollaküri (sık idrara çıkma)", "kategori": "Üriner"},
    {"id": "S065", "ad": "Hematüri", "kategori": "Üriner"},
    {"id": "S066", "ad": "Üriner retansiyon", "kategori": "Üriner"},
    {"id": "S067", "ad": "İdrar tutamama", "kategori": "Üriner"},
    {"id": "S068", "ad": "Kötü kokulu idrar", "kategori": "Üriner"},
    {"id": "S069", "ad": "Böğür ağrısı", "kategori": "Üriner"},
    {"id": "S070", "ad": "Suprapubik ağrı", "kategori": "Üriner"},

    {"id": "S071", "ad": "Döküntü", "kategori": "Cilt"},
    {"id": "S072", "ad": "Kaşıntı", "kategori": "Cilt"},
    {"id": "S073", "ad": "Ürtiker", "kategori": "Cilt"},
    {"id": "S074", "ad": "Anjioödem", "kategori": "Cilt"},
    {"id": "S075", "ad": "Eritema", "kategori": "Cilt"},
    {"id": "S076", "ad": "Veziküler lezyon", "kategori": "Cilt"},
    {"id": "S077", "ad": "Ksantalezma", "kategori": "Cilt"},
    {"id": "S078", "ad": "Ksantoma", "kategori": "Cilt"},
    {"id": "S079", "ad": "Deride kuruluk", "kategori": "Cilt"},
    {"id": "S080", "ad": "Yaraların geç iyileşmesi", "kategori": "Cilt"},
    {"id": "S081", "ad": "Saç ve tırnaklarda kırılma", "kategori": "Cilt"},

    {"id": "S082", "ad": "Eklem ağrısı/artralji", "kategori": "Kas"},
    {"id": "S083", "ad": "Eklem şişliği", "kategori": "Kas"},
    {"id": "S084", "ad": "Bel ağrısı", "kategori": "Kas"},
    {"id": "S085", "ad": "Sırt ağrısı", "kategori": "Kas"},
    {"id": "S086", "ad": "Sabah tutukluğu", "kategori": "Kas"},
    {"id": "S087", "ad": "Ekstremitelerde ağrı", "kategori": "Kas"},
    {"id": "S088", "ad": "Kas spazmı", "kategori": "Kas"},
    {"id": "S089", "ad": "Krepitasyon", "kategori": "Kas"},

    {"id": "S090", "ad": "Kulak ağrısı", "kategori": "KBB"},
    {"id": "S091", "ad": "İşitme kaybı/sağırlık", "kategori": "KBB"},
    {"id": "S092", "ad": "Kulak çınlaması/tinnitus", "kategori": "KBB"},
    {"id": "S093", "ad": "Vertigo", "kategori": "KBB"},
    {"id": "S094", "ad": "Koku alma bozukluğu", "kategori": "KBB"},
    {"id": "S095", "ad": "Lenfadenopati", "kategori": "KBB"},
    {"id": "S096", "ad": "Yüzde ağrı/basınç", "kategori": "KBB"},

    {"id": "S097", "ad": "Görme bozukluğu/bulanık görme", "kategori": "Göz"},
    {"id": "S098", "ad": "Körlük", "kategori": "Göz"},
    {"id": "S099", "ad": "Çift görme/diplopi", "kategori": "Göz"},
    {"id": "S100", "ad": "Fotofobi", "kategori": "Göz"},
    {"id": "S101", "ad": "Konjonktivit", "kategori": "Göz"},

    {"id": "S102", "ad": "Polidipsi (aşırı susama)", "kategori": "Endokrin"},
    {"id": "S103", "ad": "Polifaji (aşırı yeme)", "kategori": "Endokrin"},
    {"id": "S104", "ad": "Ateş basması", "kategori": "Endokrin"},
    {"id": "S105", "ad": "Kilo artışı", "kategori": "Endokrin"},
    {"id": "S106", "ad": "Erektil disfonksiyon", "kategori": "Endokrin"},
    {"id": "S107", "ad": "Vajinal kuruluk", "kategori": "Endokrin"},
    {"id": "S108", "ad": "Libido azalması", "kategori": "Endokrin"},

    {"id": "S109", "ad": "Anksiyete/kaygı", "kategori": "Psik."},
    {"id": "S110", "ad": "Depresyon/çökkün duygudurum", "kategori": "Psik."},
    {"id": "S111", "ad": "Panik atak", "kategori": "Psik."},
    {"id": "S112", "ad": "Uyku bozukluğu/uykusuzluk", "kategori": "Psik."},
    {"id": "S113", "ad": "Aşırı uyku/hipersomni", "kategori": "Psik."},
    {"id": "S114", "ad": "Huzursuzluk", "kategori": "Psik."},
    {"id": "S115", "ad": "Sinirlilik/ajitasyon", "kategori": "Psik."},
    {"id": "S116", "ad": "İntihar düşüncesi", "kategori": "Psik."},
    {"id": "S117", "ad": "Obsesyon/takıntılı düşünceler", "kategori": "Psik."},
    {"id": "S118", "ad": "Kompulsiyon/yineleyici davranışlar", "kategori": "Psik."},
    {"id": "S119", "ad": "Fobi/korku", "kategori": "Psik."},
    {"id": "S120", "ad": "Ölüm korkusu", "kategori": "Psik."},
    {"id": "S121", "ad": "İlgi kaybı/zevk alamama", "kategori": "Psik."},

    {"id": "S122", "ad": "Menstrüel düzensizlik", "kategori": "Jine."},
    {"id": "S123", "ad": "Dismenore", "kategori": "Jine."},
    {"id": "S124", "ad": "Aşırı menstrüel kanama", "kategori": "Jine."},
    {"id": "S125", "ad": "Vajinal akıntı", "kategori": "Jine."},
    {"id": "S126", "ad": "Vajinal kaşıntı", "kategori": "Jine."},
    {"id": "S127", "ad": "Cinsel ilişkide ağrı/disparoni", "kategori": "Jine."},
    {"id": "S128", "ad": "Genital bölgede ağrı", "kategori": "Jine."},
    {"id": "S129", "ad": "Gebelikte kusma", "kategori": "Jine."}
  ],

  "tahliller": [
    {"id": "T001", "ad": "Tam kan sayımı", "kategori": "Hematoloji"},
    {"id": "T002", "ad": "Hemoglobin (Hb)", "kategori": "Hematoloji"},
    {"id": "T003", "ad": "Hematokrit (Hct)", "kategori": "Hematoloji"},
    {"id": "T004", "ad": "MCV (Ortalama eritrosit hacmi)", "kategori": "Hematoloji"},
    {"id": "T005", "ad": "MCH (Ortalama eritrosit hemoglobini)", "kategori": "Hematoloji"},
    {"id": "T006", "ad": "MCHC", "kategori": "Hematoloji"},
    {"id": "T007", "ad": "Eritrosit sayısı (RBC)", "kategori": "Hematoloji"},
    {"id": "T008", "ad": "Lökosit sayısı (WBC)", "kategori": "Hematoloji"},
    {"id": "T009", "ad": "Trombosit sayısı (PLT)", "kategori": "Hematoloji"},
    {"id": "T010", "ad": "Sedimentasyon (ESR)", "kategori": "Hematoloji"},
    {"id": "T011", "ad": "Periferik yayma", "kategori": "Hematoloji"},
    {"id": "T012", "ad": "Retikülosit sayısı", "kategori": "Hematoloji"},

    {"id": "T013", "ad": "Açlık kan şekeri (AKŞ)", "kategori": "Biyokimya"},
    {"id": "T014", "ad": "Tokluk kan şekeri (TKŞ)", "kategori": "Biyokimya"},
    {"id": "T015", "ad": "HbA1c", "kategori": "Biyokimya"},
    {"id": "T016", "ad": "OGTT (Oral glukoz tolerans testi)", "kategori": "Biyokimya"},
    {"id": "T017", "ad": "Total kolesterol", "kategori": "Biyokimya"},
    {"id": "T018", "ad": "HDL kolesterol", "kategori": "Biyokimya"},
    {"id": "T019", "ad": "LDL kolesterol", "kategori": "Biyokimya"},
    {"id": "T020", "ad": "Trigliserid", "kategori": "Biyokimya"},
    {"id": "T021", "ad": "BUN (Kan üre nitrojeni)", "kategori": "Biyokimya"},
    {"id": "T022", "ad": "Kreatinin", "kategori": "Biyokimya"},
    {"id": "T023", "ad": "Kreatinin klerensi", "kategori": "Biyokimya"},
    {"id": "T024", "ad": "Ürik asit", "kategori": "Biyokimya"},
    {"id": "T025", "ad": "ALT (Alanin aminotransferaz)", "kategori": "Biyokimya"},
    {"id": "T026", "ad": "AST (Aspartat aminotransferaz)", "kategori": "Biyokimya"},
    {"id": "T027", "ad": "GGT (Gama glutamiltransferaz)", "kategori": "Biyokimya"},
    {"id": "T028", "ad": "ALP (Alkalen fosfataz)", "kategori": "Biyokimya"},
    {"id": "T029", "ad": "Total bilirubin", "kategori": "Biyokimya"},
    {"id": "T030", "ad": "Direkt bilirubin", "kategori": "Biyokimya"},
    {"id": "T031", "ad": "İndirekt bilirubin", "kategori": "Biyokimya"},
    {"id": "T032", "ad": "Total protein", "kategori": "Biyokimya"},
    {"id": "T033", "ad": "Albumin", "kategori": "Biyokimya"},
    {"id": "T034", "ad": "Globulin", "kategori": "Biyokimya"},
    {"id": "T035", "ad": "Amilaz", "kategori": "Biyokimya"},
    {"id": "T036", "ad": "Lipaz", "kategori": "Biyokimya"},
    {"id": "T037", "ad": "LDH (Laktat dehidrogenaz)", "kategori": "Biyokimya"},
    {"id": "T038", "ad": "CK (Kreatin kinaz)", "kategori": "Biyokimya"},
    {"id": "T039", "ad": "CK-MB", "kategori": "Biyokimya"},
    {"id": "T040", "ad": "Troponin-T", "kategori": "Biyokimya"},
    {"id": "T041", "ad": "Troponin-I", "kategori": "Biyokimya"},
    {"id": "T042", "ad": "Miyoglobin", "kategori": "Biyokimya"},
    {"id": "T043", "ad": "Demir", "kategori": "Biyokimya"},
    {"id": "T044", "ad": "Total demir bağlama kapasitesi", "kategori": "Biyokimya"},
    {"id": "T045", "ad": "Ferritin", "kategori": "Biyokimya"},
    {"id": "T046", "ad": "Vitamin B12", "kategori": "Biyokimya"},
    {"id": "T047", "ad": "Folik asit", "kategori": "Biyokimya"},

    {"id": "T048", "ad": "Sodyum (Na)", "kategori": "Elektrolit"},
    {"id": "T049", "ad": "Potasyum (K)", "kategori": "Elektrolit"},
    {"id": "T050", "ad": "Kalsiyum (Ca)", "kategori": "Elektrolit"},
    {"id": "T051", "ad": "Magnezyum (Mg)", "kategori": "Elektrolit"},
    {"id": "T052", "ad": "Klorür (Cl)", "kategori": "Elektrolit"},
    {"id": "T053", "ad": "Fosfor (P)", "kategori": "Elektrolit"},

    {"id": "T054", "ad": "TSH", "kategori": "Hormon"},
    {"id": "T055", "ad": "Serbest T3", "kategori": "Hormon"},
    {"id": "T056", "ad": "Serbest T4", "kategori": "Hormon"},
    {"id": "T057", "ad": "Total T3", "kategori": "Hormon"},
    {"id": "T058", "ad": "Total T4", "kategori": "Hormon"},
    {"id": "T059", "ad": "FSH (Folikül stimüle edici hormon)", "kategori": "Hormon"},
    {"id": "T060", "ad": "Östradiol (E2)", "kategori": "Hormon"},

    {"id": "T061", "ad": "Tam idrar incelemesi", "kategori": "İdrar"},
    {"id": "T062", "ad": "İdrar kültürü", "kategori": "İdrar"},
    {"id": "T063", "ad": "İdrarda bilirubin", "kategori": "İdrar"},
    {"id": "T064", "ad": "İdrarda ürobilinojen", "kategori": "İdrar"},
    {"id": "T065", "ad": "İdrarda mikroalbüminüri", "kategori": "İdrar"},
    {"id": "T066", "ad": "İdrar piyüri (lökosit)", "kategori": "İdrar"},
    {"id": "T067", "ad": "İdrar bakteriüri", "kategori": "İdrar"},
    {"id": "T068", "ad": "İdrar nitrit testi", "kategori": "İdrar"},
    {"id": "T069", "ad": "İdrar lökosit esteraz testi", "kategori": "İdrar"},

    {"id": "T070", "ad": "CRP (C-reaktif protein)", "kategori": "Enflamasyon"},
    {"id": "T071", "ad": "ASO (Antistreptolizin O)", "kategori": "Enflamasyon"},
    {"id": "T072", "ad": "RF (Romatoid faktör)", "kategori": "Enflamasyon"},

    {"id": "T073", "ad": "Wright testi (Brusella)", "kategori": "Seroloji"},
    {"id": "T074", "ad": "Rose Bengal testi", "kategori": "Seroloji"},
    {"id": "T075", "ad": "VDRL (Sifiliz)", "kategori": "Seroloji"},
    {"id": "T076", "ad": "RPR (Sifiliz)", "kategori": "Seroloji"},
    {"id": "T077", "ad": "HBsAg", "kategori": "Seroloji"},
    {"id": "T078", "ad": "Anti-HBs", "kategori": "Seroloji"},
    {"id": "T079", "ad": "Anti-HBc IgM", "kategori": "Seroloji"},
    {"id": "T080", "ad": "Anti-HBc IgG", "kategori": "Seroloji"},
    {"id": "T081", "ad": "Anti-toksoplazma IgM", "kategori": "Seroloji"},
    {"id": "T082", "ad": "HIV testi", "kategori": "Seroloji"},

    {"id": "T083", "ad": "Boğaz kültürü", "kategori": "Mikrobiyoloji"},
    {"id": "T084", "ad": "Balgam Gram boyama", "kategori": "Mikrobiyoloji"},
    {"id": "T085", "ad": "Balgam tüberküloz basili", "kategori": "Mikrobiyoloji"},
    {"id": "T086", "ad": "Dışkı mikroskopisi (parazit)", "kategori": "Mikrobiyoloji"},
    {"id": "T087", "ad": "Kan kültürü", "kategori": "Mikrobiyoloji"},

    {"id": "T088", "ad": "EKG (Elektrokardiyografi)", "kategori": "Görüntüleme"},
    {"id": "T089", "ad": "Telekardiyografi", "kategori": "Görüntüleme"},
    {"id": "T090", "ad": "Akciğer grafisi (PA)", "kategori": "Görüntüleme"},
    {"id": "T091", "ad": "Ekokardiyografi", "kategori": "Görüntüleme"},
    {"id": "T092", "ad": "Ultrasonografi (USG)", "kategori": "Görüntüleme"},

    {"id": "T093", "ad": "Spirometri (SFT)", "kategori": "Fonksiyon"},
    {"id": "T094", "ad": "FEV1", "kategori": "Fonksiyon"},
    {"id": "T095", "ad": "FVC", "kategori": "Fonksiyon"},
    {"id": "T096", "ad": "FEV1/FVC oranı", "kategori": "Fonksiyon"},
    {"id": "T097", "ad": "Peak flow (PEF)", "kategori": "Fonksiyon"},

    {"id": "T098", "ad": "Gebelik testi", "kategori": "Diğer"},
    {"id": "T099", "ad": "Kan grubu (ABO ve Rh)", "kategori": "Diğer"},
    {"id": "T100", "ad": "PPD (Tüberkülin deri testi)", "kategori": "Diğer"}
  ],

  "kategoriler": {
    "semptom_kategorileri": [
      {"kod": "Tümü", "emoji": "🔘"},
      {"kod": "Genel", "emoji": "🧍"},
      {"kod": "Nöro", "emoji": "🧠"},
      {"kod": "Solunum", "emoji": "🫁"},
      {"kod": "Kalp", "emoji": "❤️"},
      {"kod": "GİS", "emoji": "🫃"},
      {"kod": "Üriner", "emoji": "🚽"},
      {"kod": "Cilt", "emoji": "🖐️"},
      {"kod": "Kas", "emoji": "🦴"},
      {"kod": "KBB", "emoji": "👂"},
      {"kod": "Göz", "emoji": "👁️"},
      {"kod": "Endokrin", "emoji": "⚗️"},
      {"kod": "Psik.", "emoji": "🧘"},
      {"kod": "Jine.", "emoji": "♀️"}
    ],
    "tahlil_kategorileri": [
      "Hematoloji",
      "Biyokimya",
      "Elektrolit",
      "Hormon",
      "İdrar",
      "Enflamasyon",
      "Seroloji",
      "Mikrobiyoloji",
      "Görüntüleme",
      "Fonksiyon",
      "Diğer"
    ]
  },

  "kaynak": "T.C. Sağlık Bakanlığı Birinci Basamağa Yönelik Tanı ve Tedavi Rehberi (2003)"
}